#! /usr/bin/env perl
use strict;
use warnings;

my @OPTS = ('--keep-exit-code', 'pugs');

if (@ARGV) {
    my $file = $ARGV[0];
    if (! -e $file) {
        my $spec = "t/spec/$file";
        if (-e $spec) {
            $ARGV[0] = $spec;
        }
    }
}

my $nt = `t/spec/fudge @OPTS @ARGV`;
system("/home/coke/.cabal/bin/pugs", split ' ', $nt);
