#! /usr/bin/env perl
use strict;
use warnings;

my @OPTS = ('--keep-exit-code', 'pugs');

if (@ARGV) {
    my $file = $ARGV[0];
    if (! -e $file) {
        my $spec = "t/spec/$file";
        if (-e $spec) {
            $ARGV[0] = $spec;
        }
    }
}

my $nt = `t/spec/fudge @OPTS @ARGV`;
$ENV{PUGS_USE_EXTERNAL_TEST}=1;
if ($^O eq 'darwin') {
    $ENV{LC_ALL}="en_US.ISO8859-1";
}
else {
    $ENV{LC_ALL}="en_US.ISO-8859-1";
}
system("./Pugs/pugs", "-IPugs/ext/Test/lib", split ' ', $nt);
